checking diff for pr_id: 138
diff --git a/Dockerfile b/Dockerfile
index e373cd8..8add29b 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -10,7 +10,7 @@ RUN apk add --no-cache curl=~7 git=~2 && \
     chmod +x user.sh && \
     ./user.sh
 
-FROM alpine:3.17.1
+FROM alpine:3.20.1
 ENV BIN=/usr/local/bin/
 ENV USERNAME=dip
 ENV BASE=/opt/${USERNAME}